#!/bin/bash

# Define repositories and their respective folders
declare -A REPOS=(
    ["cybrosys"]="https://github.com/CybroOdoo/CybroAddons https://github.com/CybroOdoo/OpenHRMS"
    ["mcm"]="git@github.com:McMillan-Woods-Global/odoo_enterprise_addons.git git@github.com:McMillan-Woods-Global/mcm_gen_modules.git"
    ["oca"]="https://github.com/OCA/account-financial-reporting https://github.com/OCA/account-financial-tools https://github.com/OCA/account-invoicing https://github.com/OCA/account-payment https://github.com/OCA/account-reconcile https://github.com/OCA/reporting-engine https://github.com/OCA/sale-workflow https://github.com/OCA/server-tools https://github.com/OCA/server-ux https://github.com/OCA/web"
    ["odoo-mates"]="https://github.com/odoomates/odooapps"
    ["others"]="https://github.com/muhlhel/myfree"
)

# Create the main directory named "extra-addons"
MAIN_DIR="extra-addons"
mkdir -p "$MAIN_DIR"
cd "$MAIN_DIR" || exit

# Loop through each category and clone repositories
for category in "${!REPOS[@]}"; do
    echo "Creating folder: $category"
    mkdir -p "$category"
    cd "$category" || exit

    for repo in ${REPOS[$category]}; do
        repo_name=$(basename "$repo" .git)  # Get repository name
        echo "Cloning $repo_name (branch 17.0)..."
        git clone -b 17.0 --single-branch "$repo"
    done

    cd ..
done

echo "✅ All repositories cloned successfully into '$MAIN_DIR'!"
